### ISSUE TITLE
Error while while attempting to run diagnostics "Characteristic b833d4f"  and Error while attempting to connect via Bluetooth "Characteristic 398168aa" 

### ISSUE THREAD

**Issue by salmanfarisvp** [NebraLtd/hm-config#46]
One of the customers received two different error codes, one while attempting to run diagnostics, the other while attempting to connect via Bluetooth.

![image](https://user-images.githubusercontent.com/11945360/124311892-12aa7f00-db8c-11eb-916f-14f164271f58.png)

![image](https://user-images.githubusercontent.com/11945360/124311916-1b9b5080-db8c-11eb-8d57-eeea91fbecad.png)

**Comment by shawaj** [comment]
You can see the error codes here
https://github.com/NebraLtd/hm-config/blob/master/config-python/uuids.py

**Comment by shawaj** [comment]
Second error relates to #16

**Comment by posterzh** [comment]
2 type of Errors
- Characteristic error while connecting WiFi is fixed by https://github.com/NebraLtd/hm-config/pull/129
- Characteristic error while running the diagnostics occurs because `DiagnosticsCharacteristic::ReadValue()` takes too much time. I am trying to find the exact timeout value in the BLE read/write characterics, but it's obvious that read/write operation should be finished quickly and it's needed to use `notify` operation for reading values that takes longer time.

The two most time consuming part of this method is 
- getting the diagnostics report by `com.helium.Miner` dbus object 
There is a git commit that makes the `hm-config` to wait until the `diagnostics` to be ready. But still even if `diagnostics` are ready, pulling the diagnostics report dynamically when it's asked by BLE read operation seems to take too much time.
I recommend to use cache for `diagnostics` report since Helium app use `read` operation but not `notify` when getting the diagnostics report.
- getting the IP by `nmcli` command invocation.

**Comment by posterzh** [comment]
@marvinmarnold `diagnostics` data is cached in the `diagnostics` service web endpoint, so it's not reasonable to introduce another level of caching. 
The caching in 'diagnostics' endpoint is introduced at 10/21/2021.
- https://github.com/NebraLtd/hm-diag/commit/9ba78481584cacf8bb5aede8faae136da80085e1#diff-04b1aca2fd0e3d6dca6921bc407e7e1cf9b6c93e823d1d31591fcfd6b398304aR41
- https://github.com/NebraLtd/hm-diag/commit/cca09908bcb90ee376c99b3e76ef823b90eecbab#diff-04b1aca2fd0e3d6dca6921bc407e7e1cf9b6c93e823d1d31591fcfd6b398304aR41

And this issue is reported at 06/02/2021. So this issue may be already fixed.

To confirm this is really fixed, I would like to profile the execution times for each line in the `DiagnosticsCharacteristic::ReadValue()` method.
If this issue is still around here, then I will try to increase the timeout value of BLE read/write operation to tolerate the time needed by diagnostics.

**Comment by marvinmarnold** [comment]
@posterzh is it possible to improve the error message? Its always possible diagnostics requests fail for whatever reason.

**Comment by posterzh** [comment]
@marvinmarnold yes, this issue is the best place to introduce the custom error message.

**Comment by posterzh** [comment]
@marvinmarnold In `hm-config/DiagnosticsCharacteristic`, it's impossible to return a custom error message to Helium app.

Helium app always expects the `diagnostics_v1` protobuf response when calling the diagnostics feature through BLE. So `DiagnosticsCharacteristic::ReadValue()` method should return a response in accordance with `diagnostics_v1` protobuf even if in the case of exception occurring.
